# Generated by https://github.com/abbyssoul/kinjo/blob/main/scripts/release/update-homebrew-formula.sh
# for each release. Edit the template there: the next release overwrites
# changes made here.
class Kinjo < Formula
  desc "TUI and command launcher for local network mDNS services"
  homepage "https://github.com/abbyssoul/kinjo"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/abbyssoul/kinjo/releases/download/v0.3.12/kinjo-0.3.12-aarch64-apple-darwin.tar.gz"
      sha256 "e773cdea5811dc9140cebfacb133ce6d58e466d68e07d0ab19395754aad0d1f2"
    end

    on_intel do
      url "https://github.com/abbyssoul/kinjo/releases/download/v0.3.12/kinjo-0.3.12-x86_64-apple-darwin.tar.gz"
      sha256 "b8f1cce1e78c370f86514aee4a79494e97612c64a81ebcae3832ec94e52836fe"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/abbyssoul/kinjo/releases/download/v0.3.12/kinjo-0.3.12-aarch64-unknown-linux-musl.tar.gz"
      sha256 "691d20dc29406543e6f37c4f89811f5b83d9e9323159b2030bbb257233583970"
    end

    on_intel do
      url "https://github.com/abbyssoul/kinjo/releases/download/v0.3.12/kinjo-0.3.12-x86_64-unknown-linux-musl.tar.gz"
      sha256 "c647afe089dfc279777d6e52ffe72636ca7cacb628d4b706aea1ab5a665b6151"
    end
  end

  # kinjo discovers commands in `share/kinjo/commands` relative to its own
  # binary, so installing into pkgshare/"commands" makes the bundled defaults
  # work out of the box — no post-install copying.
  def install
    bin.install "kinjo"
    (pkgshare/"commands").install Dir["commands/*.toml"]
  end

  def caveats
    <<~EOS
      Default command definitions were installed to:
        #{opt_pkgshare}/commands

      kinjo discovers them there automatically. To customize a command, copy
      it to ~/.config/kinjo/commands (or $XDG_CONFIG_HOME/kinjo/commands) and
      edit it; a user command with the same name overrides the bundled one.
    EOS
  end

  test do
    # `ssh` is one of the bundled defaults; seeing it proves the binary
    # discovered the commands installed under pkgshare.
    assert_match "ssh", shell_output("#{bin}/kinjo list-commands")
  end
end
